### ISSUE TITLE
Add foot/joint velocity to fkRobotState and ikRobotState

### ISSUE THREAD

**Issue by jcnorby** [robomechanics/spirit-software#136]

**Comment by mturski** [comment]
Update foot_jacobians.cpp with Eigen::Map<>(), and consider fk and ik velocities per leg.

**Comment by jcnorby** [comment]
@yanhaoy I see that you've added this in the update-inverse-dynamics branch, thanks again for doing that. Do you think we could write the legIKVel function within the pre-existing kinematics class? Then in ikRobotState we just call that function (which is how it handles the position IK).

Also once we do that we can update the tests in test_kinematics.cpp to generate random sets of joint velocities, map them to end effector velocities, then back again to make sure everything is working properly.
