### ISSUE TITLE
Clean up roslaunch files

### ISSUE THREAD

**Issue by nikolaif399** [robomechanics/spirit-software#66]
Separate roslaunch files into logical units (remote.launch, robot.launch should be wrappers around smaller launch files)

**Comment by jcnorby** [comment]
Right now I'm thinking smaller launch files should be as follows. Thoughts?

- terrain_mapping.launch (terrain_map_publisher)
- planning_stack.launch (global body planner, local footstep planner)
- visualization.launch (rviz_interface and rviz)
- record.launch (rosbag record)
- mocap.launch (mocap_optitrack)

**Comment by nikolaif399** [comment]
Do we need an estimation/contact detection launch?

**Comment by jcnorby** [comment]
Ah, yes. Updated.

**Comment by nikolaif399** [comment]
Looks good to me
