### ISSUE TITLE
Refine open loop controller

### ISSUE THREAD

**Issue by nikolaif399** [robomechanics/spirit-software#70]
Refine open loop controller with better end effector trajectories and gains for better open loop walking.

**Comment by jcnorby** [comment]
Is this still going to happen, or has it served its purpose? We can close the issue if we no longer need it.

**Comment by nikolaif399** [comment]
This should still happen, although I don't have a timetable for doing it

**Comment by jcnorby** [comment]
Okay we can leave open, I'm labeling as good first issue because presumably it will be done by whoever needs it working first.

**Comment by jcnorby** [comment]
Not needed any more, can reopen if that changes.
