### ISSUE TITLE
Fix state estimators to give joint effort in newtons rather than amps

### ISSUE THREAD

**Issue by jcnorby** [robomechanics/spirit-software#74]
Anyone could do this, really, but it would be nice to do it before it goes into the message so it only needs to be done once (rather than every area that uses that message)

**Comment by justinyim** [comment]
Shelving this for later after discussion: effort will continue to be reported in amps and converted where needed since nothing is currently using this except the logging.

**Comment by jcnorby** [comment]
If we need this later it'll probably be in the spirit_utils library to be included by any estimation nodes
